### ISSUE TITLE
[W09H03] `java.lang.NoClassDefFoundError: org/junit/platform/engine/ConfigurationParameters`

### ISSUE THREAD

**Issue by nilsreichardt** [MaximilianAnzinger/pgdp2223-tests#226]
I'm getting the following error message when I'm executing one of the tests:

```
java.lang.NoClassDefFoundError: org/junit/platform/engine/ConfigurationParameters
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
NativeConstructorAccessorImpl.java:77
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
DelegatingConstructorAccessorImpl.java:45
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
Constructor.java:499
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
ReflectAccess.java:128
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
ReflectionFactory.java:347
	at java.base/java.lang.Class.newInstance(Class.java:645)
Class.java:645
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:371)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:366)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:310)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:225)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.engine.ConfigurationParameters
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
BuiltinClassLoader.java:641
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
ClassLoaders.java:188
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
ClassLoader.java:520
	... 13 more
```

**Comment by nilsreichardt** [comment]
I fixed it by adding `testImplementation('org.junit.platform:junit-platform-launcher:1.5.2')` to my dependencies in my `build.gradle`:

```gradle
dependencies {
    implementation 'org.apache.commons:commons-lang3:3.12.0'
    api 'org.bytedeco:javacv-platform:1.5.8'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.9.1'
    testImplementation('org.junit.platform:junit-platform-launcher:1.5.2')
}
```
